trigger:
  - develop

pool:
  name: Default

variables:
  MAVEN_OPTS: "-Xmx1024m"
  -group: Grupo-de-variables-1

steps:
  - task: Maven@4  # Usa la versión más nueva
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean verify sonar:sonar'
      options: >
        -Dsonar.projectKey=hello-sonar
        -Dsonar.projectName=hello-sonar
        -Dsonar.host.url=$(SONARQUBE_URL)
        -Dsonar.login=$(SONARQUBE_TOKEN)
        -Dsonar.sources=src
        -Dsonar.java.binaries=target/classes
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
