trigger:
  - master

pool:
  name: Default

variables:
  MAVEN_OPTS: "-Xmx1024m"
  -group: Grupo-de-variables-1

steps:
  - task: SonarQubePrepare@5
    inputs:
      SonarQube: '$(SONARQUBE_URL)'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'hello-sonar'
      cliProjectName: 'hello-sonar'
      cliSources: '.'
      extraProperties: |
        sonar.login=$(SONARQUBE_TOKEN)

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean verify'
      options: '-DskipTests=false'

  - task: SonarQubeAnalyze@5

  - task: SonarQubePublish@5
    inputs:
      pollingTimeoutSec: '300'
       
